const ORDER_STATUS = Object.freeze({
  PROCESSING: "PROCESSING",
  DELIVERED: "DELIVERED",
});

const PROGRESS_STATUSES = [
  ORDER_STATUS.PROCESSING,
];

module.exports = { ORDER_STATUS, PROGRESS_STATUSES };
